import MenuItem from '../../models/MenuItem.js';

const menuItemsData = [
  // Sweet Breakfast
  {
    name: "pancake",
    price: 300,
    src: "/assets/images/menu-items/breakfast/hot-breakfast/pancake.png",
    description: "Fluffy, golden pancakes served with maple syrup and a pat of butter. Made fresh daily with our secret recipe that's been perfected over the years. A classic breakfast favorite that never disappoints.",
    addOns: ["Maple Syrup", "Butter", "Fresh Berries", "Whipped Cream", "Chocolate Chips", "Banana Slices"],
    category: "BREAKFAST",
    subcategory: "Sweet Breakfast",
  },
  {
    name: "crepes",
    price: 300,
    src: "/assets/images/menu-items/breakfast/hot-breakfast/crepes.png",
    description: "Delicate, paper-thin crepes filled with your choice of sweet or savory fillings. Light and airy, these French-style crepes are made to order and served warm. Perfect for a sophisticated breakfast experience.",
    addOns: ["Nutella", "Strawberries", "Powdered Sugar", "Lemon & Sugar", "Ham & Cheese", "Spinach & Feta"],
    category: "BREAKFAST",
    subcategory: "Sweet Breakfast",
  },
  {
    name: "french toast",
    price: 300,
    src: "/assets/images/menu-items/breakfast/hot-breakfast/frenchtoast.png",
    description: "Thick slices of brioche bread soaked in a rich custard mixture, then pan-fried to golden perfection. Served with powdered sugar, fresh berries, and a drizzle of maple syrup. A decadent morning treat.",
    addOns: ["Maple Syrup", "Powdered Sugar", "Fresh Berries", "Cinnamon", "Vanilla Ice Cream", "Bacon Strips"],
    category: "BREAKFAST",
    subcategory: "Sweet Breakfast",
  },
  {
    name: "waffle",
    price: 300,
    src: "/assets/images/menu-items/breakfast/hot-breakfast/waffle.png",
    description: "Crispy on the outside, soft on the inside - our Belgian-style waffles are made fresh to order. Served with whipped cream, fresh fruit, and your choice of syrup. A breakfast classic that's always a crowd pleaser.",
    addOns: ["Whipped Cream", "Fresh Fruit", "Maple Syrup", "Chocolate Sauce", "Ice Cream", "Nuts"],
    category: "BREAKFAST",
    subcategory: "Sweet Breakfast",
  },
  // Savory Breakfast
  {
    name: "breakfast sandwich",
    price: 350,
    src: "/assets/images/menu-items/breakfast/savory/breakfast_sandwich.png",
    description: "Hearty breakfast sandwich with eggs, cheese, and your choice of meat. Served on a toasted bun. A satisfying start to your day.",
    addOns: ["Bacon", "Sausage", "Cheese", "Avocado"],
    category: "BREAKFAST",
    subcategory: "Savory Breakfast",
  },
  {
    name: "vegetable omelette toast",
    price: 320,
    src: "/assets/images/menu-items/breakfast/savory/vegetable_omelette_toast.png",
    description: "Fluffy vegetable omelette served on crispy toast. Packed with fresh vegetables and perfectly cooked. A wholesome and satisfying breakfast.",
    addOns: ["Cheese", "Mushrooms", "Bell Peppers", "Onions", "Spinach", "Tomato"],
    category: "BREAKFAST",
    subcategory: "Savory Breakfast",
  },
  {
    name: "egg and toast",
    price: 250,
    src: "/assets/images/menu-items/breakfast/savory/egg_and_toast.png",
    description: "Perfectly cooked eggs served with crispy toast. Simple, classic, and delicious. A timeless breakfast combination.",
    addOns: ["Cheese", "Chives", "Bacon", "Butter"],
    category: "BREAKFAST",
    subcategory: "Savory Breakfast",
  },
  {
    name: "breakfast burrito",
    price: 380,
    src: "/assets/images/menu-items/breakfast/savory/breakfast_burrito.png",
    description: "Hearty breakfast burrito filled with eggs, cheese, and your choice of fillings. Wrapped in a warm tortilla. A filling and flavorful breakfast option.",
    addOns: ["Sausage", "Bacon", "Beans", "Cheese", "Sour Cream", "Salsa"],
    category: "BREAKFAST",
    subcategory: "Savory Breakfast",
  },
  {
    name: "panini",
    price: 200,
    src: "/assets/images/menu-items/breakfast/savory/panini.png",
    description: "Warm, pressed panini with your choice of fillings. Crispy on the outside, melty on the inside. A delicious breakfast option.",
    addOns: ["Cheese", "Ham", "Tomato", "Basil"],
    category: "BREAKFAST",
    subcategory: "Savory Breakfast",
  },
  // Healthy Breakfast
  {
    name: "oatmeal",
    price: 250,
    src: "/assets/images/menu-items/breakfast/healthy/oatmeal.png",
    description: "Creamy, warm oatmeal made with whole grains. A nutritious and filling breakfast that keeps you energized throughout the morning.",
    addOns: ["Fresh Berries", "Honey", "Nuts", "Banana Slices", "Cinnamon"],
    category: "BREAKFAST",
    subcategory: "Healthy",
  },
  {
    name: "spinach omelette",
    price: 280,
    src: "/assets/images/menu-items/breakfast/healthy/spinach_omlete.png",
    description: "Light and fluffy omelette packed with fresh spinach. A protein-rich, healthy breakfast option that's both delicious and nutritious.",
    addOns: ["Cheese", "Mushrooms", "Tomato", "Feta Cheese"],
    category: "BREAKFAST",
    subcategory: "Healthy",
  },
  {
    name: "caprese salad",
    price: 300,
    src: "/assets/images/menu-items/breakfast/healthy/caprese_salad.png",
    description: "Fresh caprese salad with ripe tomatoes, mozzarella, and basil. A light, refreshing, and healthy breakfast option.",
    addOns: ["Balsamic Glaze", "Olive Oil", "Basil", "Arugula"],
    category: "BREAKFAST",
    subcategory: "Healthy",
  },
  {
    name: "salad bowl",
    price: 320,
    src: "/assets/images/menu-items/breakfast/healthy/salad_bowl.png",
    description: "Fresh mixed greens with a variety of vegetables. A wholesome, nutrient-packed breakfast that's both satisfying and healthy.",
    addOns: ["Grilled Chicken", "Avocado", "Nuts", "Dressing", "Feta Cheese"],
    category: "BREAKFAST",
    subcategory: "Healthy",
  },
  // Cakes & Cheesecakes
  {
    name: "strawberry cake",
    price: 360,
    src: "/assets/images/menu-items/dessert/cakes_cheesecakes/strawberry_cake.png",
    description: "Moist vanilla cake layered with fresh strawberries and creamy frosting. A classic dessert that's both beautiful and delicious, perfect for any celebration.",
    addOns: ["Fresh Strawberries", "Whipped Cream", "Chocolate Sauce", "Vanilla Frosting", "Strawberry Glaze", "Powdered Sugar"],
    category: "DESSERTS",
    subcategory: "Cakes & Cheesecakes",
  },
  {
    name: "blueberry cheesecake",
    price: 380,
    src: "/assets/images/menu-items/dessert/cakes_cheesecakes/blueberry_cheesecake.png",
    description: "Creamy, rich cheesecake topped with a generous layer of fresh blueberry compote. Smooth texture with a perfect balance of sweet and tangy flavors.",
    addOns: ["Blueberry Compote", "Whipped Cream", "Graham Cracker Crumbs", "Fresh Blueberries", "Lemon Zest", "Vanilla Sauce"],
    category: "DESSERTS",
    subcategory: "Cakes & Cheesecakes",
  },
  {
    name: "strawberry swiss roll",
    price: 350,
    src: "/assets/images/menu-items/dessert/cakes_cheesecakes/strawberry_swissroll.png",
    description: "Delicious strawberry Swiss roll with a light, fluffy sponge cake rolled with creamy strawberry filling. A classic dessert that's both elegant and satisfying. Perfect for any occasion.",
    addOns: ["Whipped Cream", "Chocolate Sauce", "Strawberries", "Powdered Sugar", "Vanilla Ice Cream", "Caramel Drizzle"],
    category: "DESSERTS",
    subcategory: "Cakes & Cheesecakes",
  },
  {
    name: "blueberry swiss roll",
    price: 350,
    src: "/assets/images/menu-items/dessert/cakes_cheesecakes/blueberry_swissroll.png",
    description: "Delicious blueberry Swiss roll with a light, fluffy sponge cake rolled with creamy blueberry filling. A delightful twist on the classic Swiss roll.",
    addOns: ["Whipped Cream", "Blueberry Compote", "Fresh Blueberries", "Powdered Sugar", "Vanilla Ice Cream", "Lemon Zest"],
    category: "DESSERTS",
    subcategory: "Cakes & Cheesecakes",
  },
  {
    name: "chocolate swiss roll",
    price: 360,
    src: "/assets/images/menu-items/dessert/cakes_cheesecakes/chocolate_swissroll.png",
    description: "Rich chocolate Swiss roll with a moist chocolate sponge cake rolled with creamy chocolate filling. A decadent dessert for chocolate lovers.",
    addOns: ["Whipped Cream", "Chocolate Sauce", "Chocolate Chips", "Powdered Sugar", "Vanilla Ice Cream", "Caramel Drizzle"],
    category: "DESSERTS",
    subcategory: "Cakes & Cheesecakes",
  },
  {
    name: "strawberry cheesecake",
    price: 380,
    src: "/assets/images/menu-items/dessert/cakes_cheesecakes/strawberry_cheesecake.png",
    description: "Creamy, rich cheesecake topped with fresh strawberries and strawberry compote. Smooth texture with a perfect balance of sweet and tangy flavors.",
    addOns: ["Strawberry Compote", "Whipped Cream", "Graham Cracker Crumbs", "Fresh Strawberries", "Lemon Zest", "Vanilla Sauce"],
    category: "DESSERTS",
    subcategory: "Cakes & Cheesecakes",
  },
  {
    name: "chocolate cake",
    price: 370,
    src: "/assets/images/menu-items/dessert/cakes_cheesecakes/chocolate_cake.png",
    description: "Rich, moist chocolate cake with creamy chocolate frosting. A decadent dessert that's perfect for chocolate enthusiasts. Layers of pure chocolate indulgence.",
    addOns: ["Chocolate Frosting", "Whipped Cream", "Chocolate Chips", "Strawberries", "Caramel Drizzle", "Powdered Sugar"],
    category: "DESSERTS",
    subcategory: "Cakes & Cheesecakes",
  },
  // Pastries
  {
    name: "croissant",
    price: 200,
    src: "/assets/images/menu-items/dessert/pastries/croissant.png",
    description: "Buttery, flaky French croissant baked fresh daily. Golden brown layers that melt in your mouth. Perfect with coffee or as a standalone treat.",
    addOns: ["Butter", "Jam", "Chocolate Spread", "Honey", "Almond Paste", "Fresh Berries"],
    category: "DESSERTS",
    subcategory: "Pastries",
  },
  {
    name: "cinnamon rolls",
    price: 250,
    src: "/assets/images/menu-items/dessert/pastries/cinnamon_rolls.png",
    description: "Warm, gooey cinnamon rolls fresh from the oven, drizzled with creamy vanilla glaze. Made with our signature dough that's soft, fluffy, and perfectly spiced with cinnamon. A sweet indulgence that pairs perfectly with your morning coffee.",
    addOns: ["Vanilla Glaze", "Cream Cheese Frosting", "Raisins", "Walnuts", "Extra Cinnamon", "Caramel Drizzle"],
    category: "DESSERTS",
    subcategory: "Pastries",
  },
  {
    name: "eclairs",
    price: 280,
    src: "/assets/images/menu-items/dessert/pastries/eclairs.png",
    description: "Elegant French eclairs filled with rich cream and topped with smooth chocolate glaze. A sophisticated dessert that's both light and indulgent.",
    addOns: ["Chocolate Glaze", "Vanilla Cream", "Caramel Drizzle", "Fresh Berries", "Whipped Cream", "Powdered Sugar"],
    category: "DESSERTS",
    subcategory: "Pastries",
  },
  {
    name: "palmier",
    price: 180,
    src: "/assets/images/menu-items/dessert/pastries/palmier.png",
    description: "Crispy, buttery palmier cookies with a delicate caramelized sugar coating. A classic French pastry that's light, flaky, and perfectly sweet.",
    addOns: ["Powdered Sugar", "Chocolate Drizzle", "Cinnamon Sugar", "Vanilla Glaze"],
    category: "DESSERTS",
    subcategory: "Pastries",
  },
  // Cookies & Donuts
  {
    name: "donut",
    price: 150,
    src: "/assets/images/menu-items/dessert/cookies_donuts/donut.png",
    description: "Classic glazed donut with a soft, fluffy texture. Sweet and satisfying, perfect for a quick treat or paired with your morning coffee.",
    addOns: ["Chocolate Glaze", "Sprinkles", "Powdered Sugar", "Cinnamon Sugar", "Vanilla Glaze", "Maple Glaze"],
    category: "DESSERTS",
    subcategory: "Cookies & Donuts",
  },
  {
    name: "chocolate chip cookie",
    price: 120,
    src: "/assets/images/menu-items/dessert/cookies_donuts/chocolatechip_cookie.png",
    description: "Classic chocolate chip cookie with gooey chocolate chips. Baked fresh to golden perfection. A timeless treat that's crispy on the edges and chewy in the center.",
    addOns: ["Extra Chocolate Chips", "Vanilla Ice Cream", "Caramel Drizzle", "Nuts"],
    category: "DESSERTS",
    subcategory: "Cookies & Donuts",
  },
  {
    name: "sugar cookie",
    price: 100,
    src: "/assets/images/menu-items/dessert/cookies_donuts/sugar_cookie.png",
    description: "Soft, buttery sugar cookie with a delicate sweetness. Perfectly baked and decorated. A simple, classic treat that's always a favorite.",
    addOns: ["Icing", "Sprinkles", "Chocolate Drizzle", "Vanilla Glaze"],
    category: "DESSERTS",
    subcategory: "Cookies & Donuts",
  },
  // Fresh Fruit & Tarts
  {
    name: "banana",
    price: 100,
    src: "/assets/images/menu-items/dessert/fresh_fruit_tarts/banana.png",
    description: "Fresh, ripe banana - a healthy and natural sweet treat. Perfect for a light dessert or as a nutritious addition to your meal.",
    addOns: ["Chocolate Sauce", "Honey", "Peanut Butter", "Yogurt", "Granola", "Cinnamon"],
    category: "DESSERTS",
    subcategory: "Fresh Fruit & Tarts",
  },
  {
    name: "fruit tart",
    price: 320,
    src: "/assets/images/menu-items/dessert/fresh_fruit_tarts/fruit_tart.png",
    description: "Beautiful fruit tart with a buttery pastry crust, creamy custard filling, and an artful arrangement of fresh seasonal fruits. A visually stunning and delicious dessert.",
    addOns: ["Fresh Berries", "Kiwi", "Mango", "Whipped Cream", "Honey Drizzle", "Mint Leaves"],
    category: "DESSERTS",
    subcategory: "Fresh Fruit & Tarts",
  },
  // Hot Tea
  {
    name: "black tea",
    price: 150,
    src: "/assets/images/menu-items/drinks/hot_tea/black_tea.png",
    description: "Classic black tea brewed to perfection. A comforting and energizing beverage that pairs well with any meal. Served hot with your choice of milk and sugar.",
    addOns: ["Milk", "Sugar", "Honey", "Lemon", "Ginger", "Cardamom"],
    category: "BEVERAGES",
    subcategory: "Hot Tea",
  },
  {
    name: "lemon tea",
    price: 150,
    src: "/assets/images/menu-items/drinks/hot_tea/lemon_tea.png",
    description: "Refreshing lemon tea with a zesty twist. A perfect blend of tea and fresh lemon that's both soothing and invigorating. Great for starting your day or as an afternoon pick-me-up.",
    addOns: ["Honey", "Mint", "Ginger", "Sugar", "Lemon Slice", "Ice"],
    category: "BEVERAGES",
    subcategory: "Hot Tea",
  },
  {
    name: "pink tea",
    price: 180,
    src: "/assets/images/menu-items/drinks/hot_tea/pink_tea.png",
    description: "Traditional pink tea, also known as Kashmiri chai. A beautiful pink-hued tea with a unique flavor profile. Served with nuts and a touch of sweetness.",
    addOns: ["Almonds", "Pistachios", "Sugar", "Cardamom", "Saffron", "Cream"],
    category: "BEVERAGES",
    subcategory: "Hot Tea",
  },
  {
    name: "matcha",
    price: 200,
    src: "/assets/images/menu-items/drinks/hot_tea/matcha.png",
    description: "Premium matcha green tea, finely ground and whisked to perfection. Rich in antioxidants with a smooth, earthy flavor. A traditional Japanese tea experience.",
    addOns: ["Honey", "Milk", "Sugar", "Vanilla", "Cinnamon"],
    category: "BEVERAGES",
    subcategory: "Hot Tea",
  },
  {
    name: "lavender tea",
    price: 180,
    src: "/assets/images/menu-items/drinks/hot_tea/lavendar_tea.png",
    description: "Soothing lavender tea with a delicate floral aroma. Calming and relaxing, perfect for unwinding after a long day. A gentle and fragrant tea experience.",
    addOns: ["Honey", "Lemon", "Mint", "Sugar", "Lavender Buds"],
    category: "BEVERAGES",
    subcategory: "Hot Tea",
  },
  // Hot Chocolate
  {
    name: "hot chocolate",
    price: 200,
    src: "/assets/images/menu-items/drinks/hot_chocolate/hot_chocolate.png",
    description: "Rich and creamy hot chocolate made with premium cocoa. Topped with whipped cream and chocolate shavings. A decadent warm beverage perfect for chilly mornings.",
    addOns: ["Whipped Cream", "Chocolate Shavings", "Marshmallows", "Cinnamon", "Caramel", "Vanilla"],
    category: "BEVERAGES",
    subcategory: "Hot Chocolate",
  },
  // Hot Coffee
  {
    name: "espresso",
    price: 180,
    src: "/assets/images/menu-items/drinks/hot_coffee/espresso.png",
    description: "Rich and bold espresso shot, perfectly extracted for a strong, aromatic coffee experience. The foundation of great coffee drinks.",
    addOns: ["Sugar", "Milk", "Cream"],
    category: "BEVERAGES",
    subcategory: "Hot Coffee",
  },
  {
    name: "latte",
    price: 220,
    src: "/assets/images/menu-items/drinks/hot_coffee/latte.png",
    description: "Smooth and creamy latte made with premium espresso and steamed milk. Topped with a delicate layer of foam. A classic coffee favorite.",
    addOns: ["Vanilla Syrup", "Caramel", "Cinnamon"],
    category: "BEVERAGES",
    subcategory: "Hot Coffee",
  },
  {
    name: "chai latte",
    price: 200,
    src: "/assets/images/menu-items/drinks/hot_coffee/chai_latte.png",
    description: "Spiced chai latte with a perfect blend of tea, milk, and aromatic spices. Warm, comforting, and full of flavor.",
    addOns: ["Honey", "Sugar", "Cardamom"],
    category: "BEVERAGES",
    subcategory: "Hot Coffee",
  },
  {
    name: "cappuccino",
    price: 200,
    src: "/assets/images/menu-items/drinks/hot_coffee/cappuccino.png",
    description: "Classic cappuccino with equal parts espresso, steamed milk, and velvety foam. A perfect balance of strong coffee and creamy texture.",
    addOns: ["Cocoa Powder", "Cinnamon", "Sugar"],
    category: "BEVERAGES",
    subcategory: "Hot Coffee",
  },
  {
    name: "americano",
    price: 180,
    src: "/assets/images/menu-items/drinks/hot_coffee/americano.png",
    description: "Bold and smooth Americano made with espresso and hot water. A clean, strong coffee that's perfect for those who love the pure coffee taste.",
    addOns: ["Milk", "Sugar", "Cream"],
    category: "BEVERAGES",
    subcategory: "Hot Coffee",
  },
  // Cold Coffee
  {
    name: "iced latte",
    price: 200,
    src: "/assets/images/menu-items/drinks/cold_coffee/iced_latte.png",
    description: "Smooth and refreshing iced latte made with premium espresso and cold milk. Perfectly balanced and served over ice. A cool pick-me-up for any time of day.",
    addOns: ["Vanilla Syrup", "Caramel Drizzle", "Whipped Cream", "Cinnamon", "Ice", "Chocolate Powder"],
    category: "BEVERAGES",
    subcategory: "Cold Coffee",
  },
  // Cold Tea
  {
    name: "boba tea",
    price: 220,
    src: "/assets/images/menu-items/drinks/cold_tea/boba_tea.png",
    description: "Refreshing boba tea with chewy tapioca pearls. A popular bubble tea with your choice of flavors. Sweet, fun, and satisfying.",
    addOns: ["Tapioca Pearls", "Jelly", "Ice", "Sugar", "Milk", "Flavor Syrup"],
    category: "BEVERAGES",
    subcategory: "Cold Tea",
  },
  // Milkshakes
  {
    name: "chocolate milkshake",
    price: 220,
    src: "/assets/images/menu-items/drinks/milkshakes/chocolate_milkshake.png",
    description: "Creamy and rich chocolate milkshake made with premium chocolate and fresh milk. Topped with whipped cream and chocolate drizzle. A classic favorite that never disappoints.",
    addOns: ["Whipped Cream", "Chocolate Sauce", "Chocolate Chips", "Cherry", "Caramel", "Vanilla Ice Cream"],
    category: "BEVERAGES",
    subcategory: "Milkshakes",
  },
  {
    name: "strawberry milkshake",
    price: 220,
    src: "/assets/images/menu-items/drinks/milkshakes/strawberry_milkshake.png",
    description: "Creamy strawberry milkshake made with fresh strawberries and premium ice cream. Topped with whipped cream and fresh strawberry slices. A classic favorite.",
    addOns: ["Whipped Cream", "Strawberry Slices", "Chocolate Sauce", "Cherry", "Vanilla Ice Cream", "Strawberry Syrup"],
    category: "BEVERAGES",
    subcategory: "Milkshakes",
  },
  // Refreshing Drinks
  {
    name: "blueberry margarita",
    price: 250,
    src: "/assets/images/menu-items/drinks/refreshing_drinks/blueberry_margarita.png",
    description: "Refreshing blueberry margarita with a perfect balance of sweet and tart. Made with fresh blueberries and served ice-cold. A delightful non-alcoholic beverage.",
    addOns: ["Blueberries", "Lime", "Ice", "Sugar Rim", "Mint", "Lemon Slice"],
    category: "BEVERAGES",
    subcategory: "Refreshing Drinks",
  },
  {
    name: "mint margarita",
    price: 250,
    src: "/assets/images/menu-items/drinks/refreshing_drinks/mint_margarita.png",
    description: "Cool and refreshing mint margarita with a burst of fresh mint flavor. Perfectly balanced with lime and a hint of sweetness. A revitalizing beverage.",
    addOns: ["Fresh Mint", "Lime", "Ice", "Sugar", "Lemon Slice", "Cucumber"],
    category: "BEVERAGES",
    subcategory: "Refreshing Drinks",
  },
  {
    name: "orange margarita",
    price: 250,
    src: "/assets/images/menu-items/drinks/refreshing_drinks/orange_margarita.png",
    description: "Zesty orange margarita with fresh orange juice and a tangy twist. Bright, citrusy, and incredibly refreshing. Perfect for a sunny day.",
    addOns: ["Orange Slice", "Lime", "Ice", "Sugar Rim", "Mint", "Lemon"],
    category: "BEVERAGES",
    subcategory: "Refreshing Drinks",
  },
  {
    name: "strawberry margarita",
    price: 250,
    src: "/assets/images/menu-items/drinks/refreshing_drinks/strawberry_margarita.png",
    description: "Sweet and fruity strawberry margarita with fresh strawberries. A delightful blend of sweet and tart flavors. Served ice-cold for maximum refreshment.",
    addOns: ["Strawberries", "Lime", "Ice", "Sugar Rim", "Mint", "Lemon Slice"],
    category: "BEVERAGES",
    subcategory: "Refreshing Drinks",
  },
  {
    name: "strawberry lemonade",
    price: 200,
    src: "/assets/images/menu-items/drinks/refreshing_drinks/strawberry_lemonade.png",
    description: "Fresh strawberry lemonade made with real strawberries and freshly squeezed lemons. Sweet, tangy, and incredibly refreshing. A perfect summer drink.",
    addOns: ["Strawberries", "Lemon Slice", "Ice", "Mint", "Sugar", "Lime"],
    category: "BEVERAGES",
    subcategory: "Refreshing Drinks",
  },
  {
    name: "sharbat",
    price: 180,
    src: "/assets/images/menu-items/drinks/refreshing_drinks/sharbat.png",
    description: "Traditional sharbat, a sweet and refreshing drink made with natural fruit flavors. Cool, hydrating, and perfect for quenching your thirst.",
    addOns: ["Ice", "Mint", "Lemon", "Rose Water", "Sugar", "Basil Seeds"],
    category: "BEVERAGES",
    subcategory: "Refreshing Drinks",
  },
];

export const seedMenuItems = async () => {
  try {
    console.log('\n=== Seeding Menu Items ===');
    await MenuItem.deleteMany({});
    console.log('Cleared existing menu items');
    
    const insertedItems = await MenuItem.insertMany(menuItemsData);
    console.log(`✅ Successfully seeded ${insertedItems.length} menu items`);
    
    return { success: true, count: insertedItems.length };
  } catch (error) {
    console.error('❌ Error seeding menu items:', error.message);
    return { success: false, error: error.message };
  }
};


