const TWO_TABLE_SIZE = { width: 225 / 1200, height: 150 / 720 };
const FOUR_TABLE_SIZE = { width: 260 / 1200, height: 180 / 720 };

const tables = [
  {
    id: 1,
    x: 360 / 1200,
    y: 560 / 720,
    width: TWO_TABLE_SIZE.width,
    height: TWO_TABLE_SIZE.height,
    src: "/assets/images/table_2.png",
    reserved_src: "assets/images/table_2_reserved.png",
    seated_src: "assets/images/table_2_seated.png",
    capacity: 2,
  },
  {
    id: 2,
    x: 360 / 1200,
    y: 40 / 720,
    width: TWO_TABLE_SIZE.width,
    height: TWO_TABLE_SIZE.height,
    src: "/assets/images/table_2.png",
    reserved_src: "assets/images/table_2_reserved.png",
    seated_src: "assets/images/table_2_seated.png",
    capacity: 2,
  },
  {
    id: 3,
    x: 0,
    y: 8 / 720,
    width: FOUR_TABLE_SIZE.width,
    height: FOUR_TABLE_SIZE.height,
    src: "/assets/images/table_4.png",
    reserved_src: "assets/images/table_4_reserved.png",
    seated_src: "assets/images/table_4_seated.png",
    capacity: 4,
  },
  {
    id: 4,
    x: 0,
    y: 540 / 720,
    width: FOUR_TABLE_SIZE.width,
    height: FOUR_TABLE_SIZE.height,
    src: "/assets/images/table_4.png",
    reserved_src: "assets/images/table_4_reserved.png",
    seated_src: "assets/images/table_4_seated.png",
    capacity: 4,
  },
  {
    id: 5,
    x: 360 / 1200,
    y: 300 / 720,
    width: TWO_TABLE_SIZE.width,
    height: TWO_TABLE_SIZE.height,
    src: "/assets/images/table_2.png",
    reserved_src: "assets/images/table_2_reserved.png",
    seated_src: "assets/images/table_2_seated.png",
    capacity: 2,
  },
  {
    id: 6,
    x: 0,
    y: 274 / 720,
    width: FOUR_TABLE_SIZE.width,
    height: FOUR_TABLE_SIZE.height,
    src: "/assets/images/table_4.png",
    reserved_src: "assets/images/table_4_reserved.png",
    seated_src: "assets/images/table_4_seated.png",
    capacity: 4,
  },
];

export default tables;
